name = "SkynetRegistry"
uuid = "3607329a-7693-45f1-b2d0-3aaa1b6280e8"
repo = "git@github.com:AUK1939/SkynetRegistry.git"
description = "My private registryAsad's Julia Lang local package repository"

[packages]
14278492-aaf9-5525-8468-49e3f68cdca1 = { name = "QuantLibjl_jll", path = "jll/Q/QuantLibjl_jll" }
7ac58d11-17a9-4d9e-923b-caf08635d133 = { name = "QuantLib", path = "Q/QuantLib" }
